// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"time"
	repository2 "webook/interactive/repository"
	cache2 "webook/interactive/repository/cache"
	dao2 "webook/interactive/repository/dao"
	service2 "webook/interactive/service"
	article2 "webook/internal/events/article"
	"webook/internal/job"
	"webook/internal/repository"
	"webook/internal/repository/cache"
	"webook/internal/repository/dao"
	"webook/internal/repository/dao/article"
	"webook/internal/service"
	"webook/internal/web"
	"webook/internal/web/jwt"
	"webook/ioc"
)

// Injectors from wire.go:

//go:generate wire
func InitWebServer() *gin.Engine {
	cmdable := InitTestRedis()
	handler := jwt.NewRedisHandler(cmdable)
	logger := InitTestLogger()
	v := ioc.GinMiddlewares(cmdable, handler, logger)
	gormDB := InitTestDB()
	userDAO := dao.NewGormUserDAO(gormDB)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository, logger)
	smsService := ioc.InitSmsService(cmdable)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewCachedCodeRepository(codeCache)
	codeService := service.NewSMSCodeService(smsService, codeRepository, logger)
	userHandler := web.NewUserHandler(userService, codeService, handler)
	articleDAO := article.NewGORMArticleDAO(gormDB)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := repository.NewArticleRepository(articleDAO, userRepository, articleCache, logger)
	client := InitKafka()
	syncProducer := NewSyncProducer(client)
	producer := article2.NewKafkaProducer(syncProducer)
	articleService := service.NewArticleService(articleRepository, logger, producer)
	interactiveDAO := dao2.NewGORMInteractiveDAO(gormDB)
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository2.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, logger)
	interactiveService := service2.NewInteractiveService(interactiveRepository, logger)
	articleHandler := web.NewArticleHandler(articleService, interactiveService, logger)
	engine := ioc.InitWebServer(v, userHandler, articleHandler)
	return engine
}

func InitArticleHandler(dao3 article.ArticleDAO) *web.ArticleHandler {
	gormDB := InitTestDB()
	userDAO := dao.NewGormUserDAO(gormDB)
	cmdable := InitTestRedis()
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache)
	articleCache := cache.NewRedisArticleCache(cmdable)
	logger := InitTestLogger()
	articleRepository := repository.NewArticleRepository(dao3, userRepository, articleCache, logger)
	client := InitKafka()
	syncProducer := NewSyncProducer(client)
	producer := article2.NewKafkaProducer(syncProducer)
	articleService := service.NewArticleService(articleRepository, logger, producer)
	interactiveDAO := dao2.NewGORMInteractiveDAO(gormDB)
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository2.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, logger)
	interactiveService := service2.NewInteractiveService(interactiveRepository, logger)
	articleHandler := web.NewArticleHandler(articleService, interactiveService, logger)
	return articleHandler
}

func InitUserSvc() service.UserService {
	gormDB := InitTestDB()
	userDAO := dao.NewGormUserDAO(gormDB)
	cmdable := InitTestRedis()
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache)
	logger := InitTestLogger()
	userService := service.NewUserService(userRepository, logger)
	return userService
}

func InitRankingService(expiration time.Duration) service.RankingService {
	gormDB := InitTestDB()
	interactiveDAO := dao2.NewGORMInteractiveDAO(gormDB)
	cmdable := InitTestRedis()
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	logger := InitTestLogger()
	interactiveRepository := repository2.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, logger)
	interactiveService := service2.NewInteractiveService(interactiveRepository, logger)
	articleDAO := article.NewGORMArticleDAO(gormDB)
	userRepository := _wireCachedUserRepositoryValue
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := repository.NewArticleRepository(articleDAO, userRepository, articleCache, logger)
	client := InitKafka()
	syncProducer := NewSyncProducer(client)
	producer := article2.NewKafkaProducer(syncProducer)
	articleService := service.NewArticleService(articleRepository, logger, producer)
	redisRankingCache := cache.NewRedisRankingCache(cmdable)
	rankingLocalCache := cache.NewRankingLocalCache()
	rankingRepository := repository.NewCachedRankingRepository(redisRankingCache, rankingLocalCache)
	rankingService := service.NewBatchRankingService(interactiveService, articleService, rankingRepository)
	return rankingService
}

var (
	_wireCachedUserRepositoryValue = &repository.CachedUserRepository{}
)

func InitJwtHdl() jwt.Handler {
	cmdable := InitTestRedis()
	handler := jwt.NewRedisHandler(cmdable)
	return handler
}

func InitJobScheduler() *job.Scheduler {
	gormDB := InitTestDB()
	cronJobDAO := dao.NewGORMJobDAO(gormDB)
	cronJobRepository := repository.NewCronJobRepositoryImpl(cronJobDAO)
	logger := InitTestLogger()
	cronJobService := service.NewCronJobService(cronJobRepository, logger)
	scheduler := job.NewScheduler(cronJobService, logger)
	return scheduler
}

// wire.go:

// 第三方依赖
var thirdProvider = wire.NewSet(
	InitTestDB, InitTestRedis, InitTestLogger,
	InitKafka, NewSyncProducer,
)

var userSvcProvider = wire.NewSet(dao.NewGormUserDAO, cache.NewRedisUserCache, repository.NewCachedUserRepository, service.NewUserService)

var articlSvcProvider = wire.NewSet(article.NewGORMArticleDAO, article2.NewKafkaProducer, cache.NewRedisArticleCache, repository.NewArticleRepository, service.NewArticleService)

var interactiveSvcProvider = wire.NewSet(service2.NewInteractiveService, repository2.NewCachedInteractiveRepository, dao2.NewGORMInteractiveDAO, cache2.NewRedisInteractiveCache)

var rankServiceProvider = wire.NewSet(service.NewBatchRankingService, repository.NewCachedRankingRepository, cache.NewRedisRankingCache, cache.NewRankingLocalCache)

var jobProviderSet = wire.NewSet(service.NewCronJobService, repository.NewCronJobRepositoryImpl, dao.NewGORMJobDAO)
